describe('Service', () => {
  it('Visit admin page', () => {
    cy.visit('/admin')
    cy.contains('[data-cy="app-title"]', 'Monggo.IO')
    cy.screenshot()
  })

  it('Visit service page', () => {
    cy.get('[data-cy="service"]').click()
    cy.contains('[data-cy="page-title"]', 'Service')
    cy.screenshot()
    cy.wait(5000)
  })

  it('Add new service', () => {
    cy.get('[data-cy="trigger-add"]').click()
    cy.get('input[name="hotel"]')
      .clear()
      .type('Hotel A{enter}')
    cy.get('input[name="category"]')
      .clear()
      .type('Common Request{enter}')
    cy.get('input[name="name"]')
      .clear()
      .type('Towel Service')
    cy.get('textarea[name="description"]')
      .clear()
      .type('Towel Service is really awesome thing to use!')
    cy.get('input[name="currency"]')
      .clear()
      .type('Indonesian Rupiah{enter}')
    cy.get('input[name="price"]')
      .clear()
      .type('99')
    cy.get('input[name="count"]')
      .clear()
      .type('10')
    cy.uploadFile('input[name="images"]', 'img/bathroom-towel.jpg', 'jpg')
    cy.get('[data-cy="dialog-action"]').click()
    cy.wait(10000)
    cy.screenshot()
  })

  it('Edit existing service', () => {
    cy.get('[data-cy="trigger-edit-towel-service"]').click()
    cy.wait(10000)
    cy.get('input[name="hotel"]')
      .clear()
      .type('Hotel B{enter}')
    cy.get('input[name="category"]')
      .clear()
      .type('Room Service{enter}')
    cy.get('input[name="name"]')
      .clear()
      .type('Towel Service Awesome')
    cy.get('textarea[name="description"]')
      .clear()
      .type('Towel Service Awesome is really awesome thing to use!')
    cy.get('input[name="currency"]')
      .clear()
      .type('{del}{del}Pound Sterling{enter}')
    cy.get('input[name="price"]')
      .clear()
      .type('10')
    cy.get('input[name="count"]')
      .clear()
      .type('5')
    cy.uploadFile('input[name="images"]', 'img/bathroom-towel-2.jpg', 'jpg')
    cy.get('[data-cy="dialog-action"]').click()
    cy.wait(10000)
    cy.screenshot()
  })

  it('Delete existing service', () => {
    cy.get('[data-cy="trigger-delete-towel-service-awesome"]').click()
    cy.get('[data-cy="delete-action"]').click()
    cy.screenshot()
  })
})
