describe('User', () => {
  it('Visit admin page', () => {
    cy.visit('/admin')
    cy.contains('[data-cy="app-title"]', 'Monggo.IO')
    cy.screenshot()
  })

  it('Visit user page', () => {
    cy.get('[data-cy="user"]').click()
    cy.contains('[data-cy="page-title"]', 'User')
    cy.screenshot()
    cy.wait(5000)
  })

  it('Edit existing user', () => {
    cy.get('[data-cy="trigger-edit-jefry-dewangga"]').click()
    cy.wait(10000)
    cy.get('input[name="name"]')
      .clear()
      .type('Jefry')
    cy.get('input[name="phone"]')
      .clear()
      .type('085123456789')
    cy.get('input[name="currency"]')
      .clear()
      .type('{del}{del}Indonesian Rupiah{enter}')
    cy.get('input[name="role"]')
      .clear()
      .type('{del}{del}Guest{enter}')
    cy.get('[data-cy="dialog-action"]').click()
    cy.wait(10000)
    cy.screenshot()
  })

  it('Edit existing user - revert back', () => {
    cy.get('[data-cy="trigger-edit-jefry"]').click()
    cy.get('input[name="name"]')
      .clear()
      .type('Jefry Dewangga')
    cy.get('input[name="phone"]').clear()
    cy.get('input[name="currency"]')
      .clear()
      .type('{del}{del}United States Dollar{enter}')
    cy.get('input[name="role"]')
      .clear()
      .type('{del}{del}Operator{enter}')
    cy.get('input[name="hotel"]')
      .clear()
      .type('{del}{del}Hotel A{enter}')
    cy.get('[data-cy="dialog-action"]').click()
    cy.wait(10000)
    cy.screenshot()
  })
})
